name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen?
        Please include screenshots if possible.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Your configuration
      description: |
        Please show us your current configurations like included or excluded entities or domains.

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of this addon are you running?
    validations:
      required: true
